### ISSUE TITLE
Support for multithreaded downloads.

### ISSUE THREAD

**Issue by aaroncspaulding** [ntivirikin/xeno-canto-py#3]
Would it be possible to get support for downloading multiple audio files concurrently?

I would be happy to write this myself and submit a pull request! Without this it takes a lot of time to download the files.

**Comment by ntivirikin** [comment]
Sorry for the late response, I will try to work on this in the coming few weeks but if you are willing please submit a pull request. I will accept it into the branch.

**Comment by aaroncspaulding** [comment]
No problem. I don't use this library now but I can still write that and submit it!

**Comment by ntivirikin** [comment]
I am rather inexperienced when it comes to multithreading, so if you have some time to work on it that would be much appreciated! I will also take a closer look at this and some others features I've been meaning to add for some time now. Thank you for the feedback!

**Comment by realzza** [comment]
> 

I have built a new python wrapper of xeno-canto api based on this repo. It supports multithreading download, as it increased the download speed enormously. See [birdData](https://github.com/realzza/birdData) for implementation. Feel free to try it out!

**Comment by realzza** [comment]
> Would it be possible to get support for downloading multiple audio files concurrently?
> 
> I would be happy to write this myself and submit a pull request! Without this it takes a lot of time to download the files.

I have built a new python wrapper of xeno-canto api. It supports multithreading download, as it increased the download speed enormously. See [birdData](https://github.com/realzza/birdData) for implementation. Feel free to try it out!

**Comment by ntivirikin** [comment]
After some further thought and research, I have decided to use asynchronous programming rather than multithreading to solve the issue of slow performance when downloading audio recordings. The issue at hand is an I/O-bound problem and can be best solved by introducing concurrent downloads with no need for multithreading.

The asyncio, aiohttp and aiofiles libraries were used to implement asynchronous operation in the latest release, please refer to the pull request linked for more information on the changes made.
